source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'WordPress-Editor-iOS-Extension_Example', :exclusive => true do
  pod 'WordPress-Editor-iOS-Extension', :path => '../'
end

target 'WordPress-Editor-iOS-Extension_Tests', :exclusive => true do
  pod 'WordPress-Editor-iOS-Extension', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
